# Generated by Django 5.1.6 on 2026-09-01 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_country_country_ref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('role', models.CharField(choices=[('super_admin', 'Super administrateur'), ('admin', 'Administrateur plateforme'), ('doo', 'Direction des opérations'), ('country_manager', 'Responsable pays'), ('owner', 'Manager / Owner'), ('controller', 'Contrôleur / Finance'), ('auditor', 'Auditeur')], max_length=32, verbose_name='Rôle')),
                ('must_change_password', models.BooleanField(default=True, help_text='Force le changement à la prochaine connexion.', verbose_name='Changement de mot de passe requis')),
                ('countries', models.ManyToManyField(blank=True, help_text='Vide pour un rôle du siège : accès à tous les pays.', related_name='profiles', to='core.country', verbose_name='Pays du périmètre')),
                ('manager', models.ForeignKey(blank=True, help_text='Référentiel métier ; un manager peut exister sans compte.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='core.manager', verbose_name='Manager associé')),
                ('teams', models.ManyToManyField(blank=True, related_name='profiles', to='core.team', verbose_name='Équipes')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Compte')),
            ],
            options={
                'verbose_name': 'Profil',
                'ordering': ['user__username'],
            },
        ),
    ]
