# Generated by Django 5.2.17 on 2026-09-04 17:39

"""Mémoire anti-rejeu du second facteur.

Le profil retient le compteur de temps (RFC 6238) du dernier code accepté :
un code déjà présenté, ou plus ancien, est refusé à la connexion comme à la
confirmation de l'enrôlement. Vide pour les comptes existants : leur
prochain code sera le premier mémorisé.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_dm_df_au_siege'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='totp_last_counter',
            field=models.BigIntegerField(blank=True, help_text='Un code déjà présenté, ou plus ancien, est refusé.', null=True, verbose_name='Dernier compteur TOTP accepté'),
        ),
    ]
