# Generated by Django 5.1.6 on 2026-09-01 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_country_country_ref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('budget_threshold', 'Seuil budgétaire atteint'), ('budget_overrun', 'Dépassement budgétaire'), ('expense_submitted', 'Dépense à contrôler'), ('expense_rejected', 'Dépense rejetée'), ('proof_missing', 'Justificatif manquant'), ('proof_incomplete', 'Justificatif incomplet'), ('reallocation_requested', 'Demande de réallocation'), ('storage_error', 'Anomalie de stockage')], max_length=32, verbose_name='Type')),
                ('level', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('critical', 'Critique')], default='info', max_length=16, verbose_name='Niveau')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('body', models.TextField(blank=True, verbose_name='Message')),
                ('link', models.CharField(blank=True, help_text="Chemin relatif dans l'application, ex. /dossiers/12.", max_length=250, verbose_name='Lien')),
                ('dedup_key', models.CharField(help_text='Empêche de notifier deux fois le même événement.', max_length=180, verbose_name="Clé d'unicité")),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lu le')),
                ('emailed_at', models.DateTimeField(blank=True, null=True, verbose_name='E-mail envoyé le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Le')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core.country', verbose_name='Pays')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read_at'], name='notificatio_recipie_564b1f_idx')],
                'constraints': [models.UniqueConstraint(fields=('recipient', 'dedup_key'), name='unique_notification_par_evenement')],
            },
        ),
    ]
