# Generated by Django 5.2.17 on 2026-10-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0006_rectification_kinds"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("budget_threshold", "Seuil budgétaire atteint"),
                    ("budget_overrun", "Dépassement budgétaire"),
                    ("expense_submitted", "Dépense à contrôler"),
                    ("expense_rejected", "Dépense rejetée"),
                    ("proof_missing", "Justificatif manquant"),
                    ("proof_incomplete", "Justificatif incomplet"),
                    ("reallocation_requested", "Demande de réallocation"),
                    ("storage_error", "Anomalie de stockage"),
                    ("dossier_reopened", "Dossier rouvert"),
                    ("rectification_requested", "Demande de rectification"),
                    ("rectification_decided", "Décision sur une rectification"),
                    ("trashed", "Mise à la corbeille"),
                ],
                max_length=32,
                verbose_name="Type",
            ),
        ),
    ]
