# Generated by Django 5.1.6 on 2026-09-01 20:40

import django.core.validators
import django.db.models.deletion
import expenses.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget', '0001_initial'),
        ('core', '0003_country_country_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('name', models.CharField(max_length=180, unique=True, verbose_name='Nom')),
                ('kind', models.CharField(choices=[('prospect', 'Prospect'), ('client', 'Client'), ('supplier', 'Fournisseur'), ('beneficiary', 'Bénéficiaire'), ('other', 'Autre')], default='beneficiary', max_length=32, verbose_name='Type')),
                ('contact', models.CharField(blank=True, max_length=180, verbose_name='Contact')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Bénéficiaire',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name="N° d'ordre")),
                ('label', models.CharField(max_length=250, verbose_name='Libellé')),
                ('date', models.DateField(verbose_name='Date')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('in_review', 'En contrôle'), ('approved', 'Validé'), ('rejected', 'Refusé'), ('closed', 'Clôturé')], default='draft', max_length=20, verbose_name='Statut')),
                ('note', models.TextField(blank=True, verbose_name='Remarque de contrôle')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dossiers', to='core.country', verbose_name='Pays')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers', to='core.manager', verbose_name='Propriétaire')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers', to='core.team', verbose_name='Équipe')),
            ],
            options={
                'verbose_name': 'Dossier de justification',
                'verbose_name_plural': 'Dossiers de justification',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('date', models.DateTimeField(verbose_name='Date et heure')),
                ('place', models.CharField(blank=True, max_length=180, verbose_name='Lieu')),
                ('title', models.CharField(max_length=250, verbose_name='Libellé de la transaction')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Dépense')),
                ('justified_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant justifié')),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces'), ('transfer', 'Virement'), ('mobile', 'Mobile money'), ('card', 'Carte'), ('check', 'Chèque'), ('other', 'Autre')], default='cash', max_length=20, verbose_name='Mode de paiement')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('in_review', 'En contrôle'), ('approved', 'Validé'), ('rejected', 'Refusé'), ('closed', 'Clôturé')], default='draft', max_length=20, verbose_name='Statut')),
                ('note', models.TextField(blank=True, verbose_name='Remarque')),
                ('created_by', models.CharField(blank=True, max_length=180, verbose_name='Saisie par')),
                ('beneficiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expenses.beneficiary', verbose_name='Prospect / bénéficiaire')),
                ('budget', models.ForeignKey(blank=True, help_text='Résolue automatiquement ; obligatoire avant validation.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='budget.budget', verbose_name='Enveloppe imputée')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='core.country', verbose_name='Pays')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='expenses.dossier', verbose_name='Dossier')),
                ('expense_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.expensetitle', verbose_name='Intitulé de dépenses')),
                ('marketing_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.marketingcategory', verbose_name='Catégorie marketing')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.manager', verbose_name='Propriétaire')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.project', verbose_name='Projet')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.team', verbose_name='Équipe')),
            ],
            options={
                'verbose_name': 'Dépense',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Proof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('file', models.FileField(upload_to=expenses.models.proof_upload_path, verbose_name='Fichier')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name="Nom d'origine")),
                ('kind', models.CharField(choices=[('receipt', 'Reçu'), ('invoice', 'Facture'), ('discharge', 'Décharge'), ('deliverable', 'Livrable'), ('other', 'Autre')], default='receipt', max_length=32, verbose_name='Type')),
                ('status', models.CharField(choices=[('received', 'Reçu'), ('incomplete', 'Incomplet'), ('to_review', 'À contrôler'), ('validated', 'Validé'), ('rejected', 'Rejeté'), ('archived', 'Archivé')], default='received', max_length=20, verbose_name='Statut')),
                ('is_complete', models.BooleanField(default=True, help_text='Reprend la nuance « reçu (justif incomplet) » du fichier source.', verbose_name='Justificatif complet')),
                ('sha256', models.CharField(db_index=True, help_text='Détecte toute modification ultérieure et les doublons.', max_length=64, verbose_name='Empreinte SHA-256')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='Taille (octets)')),
                ('content_type', models.CharField(blank=True, max_length=120, verbose_name='Type MIME')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('uploaded_by', models.CharField(blank=True, max_length=180, verbose_name='Déposé par')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motif de rejet')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='expenses.dossier', verbose_name='Dossier')),
                ('replaces', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='expenses.proof', verbose_name='Remplace')),
            ],
            options={
                'verbose_name': 'Pièce justificative',
                'verbose_name_plural': 'Pièces justificatives',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=180, verbose_name='Utilisateur')),
                ('action', models.CharField(choices=[('created', 'Création'), ('updated', 'Modification'), ('submitted', 'Soumission'), ('reviewed', 'Mise en contrôle'), ('approved', 'Validation'), ('rejected', 'Rejet'), ('closed', 'Clôture'), ('proof_uploaded', 'Dépôt de justificatif'), ('proof_replaced', 'Remplacement de justificatif'), ('downloaded', 'Téléchargement')], max_length=32, verbose_name='Action')),
                ('object_type', models.CharField(max_length=64, verbose_name="Type d'objet")),
                ('object_id', models.PositiveIntegerField(verbose_name='Identifiant')),
                ('label', models.CharField(blank=True, max_length=250, verbose_name='Libellé')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='Détail')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.CharField(blank=True, max_length=250, verbose_name='Appareil / session')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Le')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='core.country', verbose_name='Pays')),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['object_type', 'object_id'], name='expenses_au_object__ba7244_idx')],
            },
        ),
    ]
