# Generated by Django 5.1.6 on 2026-09-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Création'), ('updated', 'Modification'), ('submitted', 'Soumission'), ('reviewed', 'Mise en contrôle'), ('justified', 'Justification'), ('unjustified', 'Constat de non-justification'), ('approved', "Validation d'un justificatif"), ('rejected', "Rejet d'un justificatif"), ('deleted', "Suppression d'un brouillon"), ('closed', 'Clôture'), ('proof_uploaded', 'Dépôt de justificatif'), ('proof_replaced', 'Remplacement de justificatif'), ('downloaded', 'Téléchargement')], max_length=32, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('in_review', 'En contrôle'), ('justified', 'Justifié'), ('unjustified', 'Non justifié'), ('closed', 'Clôturé')], default='draft', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('in_review', 'En contrôle'), ('justified', 'Justifié'), ('unjustified', 'Non justifié'), ('closed', 'Clôturé')], default='draft', max_length=20, verbose_name='Statut'),
        ),
    ]
