# Generated by Django 5.1.6 on 2026-09-03 09:32

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_beneficiaire_par_pays'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Tel qu'il figure sur la pièce, dans sa devise d'origine.", max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant décaissé'),
        ),
        migrations.AddField(
            model_name='expense',
            name='original_currency',
            field=models.CharField(blank=True, help_text='Vide si la dépense a été faite dans la devise du pays.', max_length=3, verbose_name='Devise du décaissement'),
        ),
        migrations.AddField(
            model_name='expense',
            name='original_rate',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Figé à la saisie. Le conserver permet de refaire le calcul plus tard, même si la table des taux a depuis été corrigée.', max_digits=18, null=True, verbose_name='Taux appliqué'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text="Dans la devise du pays ; c'est ce montant qui pèse sur l'enveloppe.", max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Dépense'),
        ),
    ]
