# Generated by Django 5.1.6 on 2026-09-04 01:59

import logging
from decimal import Decimal, InvalidOperation
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError

import django.db.models.deletion
from django.db import migrations, models

journal = logging.getLogger(__name__)


def _exercice(expense, country):
    try:
        fuseau = ZoneInfo(country.timezone or "UTC")
    except (ZoneInfoNotFoundError, ValueError):
        fuseau = ZoneInfo("UTC")
    return expense.date.astimezone(fuseau).year


def reprendre_les_donnees(apps, schema_editor):
    """Met les lignes existantes en conformité avant de poser les contraintes.

    Les contraintes qui suivent refusent une dépense déclarée sans enveloppe
    et une devise d'origine sans taux. Une base déjà en service peut contenir
    l'une et l'autre : une ligne saisie avant que l'imputation ne soit
    automatique, ou importée avant que le taux ne soit figé. Les rejeter
    ferait échouer la migration et bloquerait tout déploiement ; les
    supprimer effacerait de l'argent dépensé. On les rattache donc, et l'on
    trace ce qui a été décidé.
    """
    Expense = apps.get_model("expenses", "Expense")
    Budget = apps.get_model("budget", "Budget")

    # 1. Dépenses déclarées sans enveloppe : on cherche l'enveloppe la plus
    #    fine qui existe (projet, équipe, manager, puis pays). S'il n'en
    #    existe aucune, une enveloppe de pays à zéro est créée : la dépense
    #    apparaît alors comme un dépassement, ce qui est la vérité.
    sans_enveloppe = (
        Expense.objects.exclude(status="draft")
        .filter(budget__isnull=True)
        .select_related("country")
    )
    for expense in sans_enveloppe:
        year = _exercice(expense, expense.country)
        enveloppes = Budget.objects.filter(
            country_id=expense.country_id, year=year, is_active=True
        )
        candidats = (
            {"project_id": expense.project_id} if expense.project_id else None,
            {"team_id": expense.team_id} if expense.team_id else None,
            {"manager_id": expense.owner_id} if expense.owner_id else None,
            {"project__isnull": True, "team__isnull": True, "manager__isnull": True},
        )
        budget = None
        for filtre in candidats:
            if filtre is None:
                continue
            budget = enveloppes.filter(**filtre).first()
            if budget is not None:
                break
        if budget is None:
            budget, _ = Budget.objects.get_or_create(
                country_id=expense.country_id,
                year=year,
                project=None,
                team=None,
                manager=None,
                defaults={"amount": Decimal("0.00")},
            )
            journal.warning(
                "Enveloppe %s %s créée à zéro pour rattacher la dépense %s "
                "déclarée sans enveloppe.",
                expense.country.name, year, expense.pk,
            )
        expense.budget = budget
        expense.save(update_fields=["budget"])

    # 2. Devise d'origine incomplète : le taux se déduit des deux montants
    #    quand ils existent ; sinon la mention est déplacée dans la note,
    #    pour ne pas la perdre, et les champs sont vidés.
    coherentes = models.Q(
        original_currency="", original_amount__isnull=True, original_rate__isnull=True
    ) | (
        ~models.Q(original_currency="")
        & models.Q(original_amount__isnull=False, original_rate__isnull=False)
    )
    for expense in Expense.objects.exclude(coherentes):
        taux = None
        if expense.original_currency and expense.original_amount:
            try:
                taux = (expense.amount / expense.original_amount).quantize(
                    Decimal("0.000001")
                )
            except (InvalidOperation, ZeroDivisionError):
                taux = None
        if taux is not None and taux > 0:
            expense.original_rate = taux
        else:
            mention = (
                f"Décaissement d'origine : {expense.original_amount} "
                f"{expense.original_currency or '?'} (taux inconnu, reprise)."
            )
            expense.note = f"{expense.note}\n{mention}".strip()
            expense.original_currency = ""
            expense.original_amount = None
            expense.original_rate = None
        expense.save(
            update_fields=["original_currency", "original_amount", "original_rate", "note"]
        )

    # Les clés étrangères de PostgreSQL sont vérifiées en fin de transaction ;
    # tant que ces vérifications sont en attente, la table ne peut pas être
    # modifiée, et les contraintes qui suivent échoueraient. On les force ici.
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("SET CONSTRAINTS ALL IMMEDIATE")


class Migration(migrations.Migration):

    # La reprise des données lit les sous-enveloppes (projet, équipe, manager)
    # et le drapeau d'activité des enveloppes : il faut l'état final de
    # ``budget``.
    dependencies = [
        ('expenses', '0006_auditlog_imported'),
        ('budget', '0004_controle_et_integrite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at', '-pk'], 'verbose_name': "Journal d'audit", 'verbose_name_plural': "Journal d'audit"},
        ),
        migrations.AlterModelOptions(
            name='dossier',
            options={'ordering': ['-date', '-created_at', '-pk'], 'verbose_name': 'Dossier de justification', 'verbose_name_plural': 'Dossiers de justification'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', '-created_at', '-pk'], 'verbose_name': 'Dépense'},
        ),
        migrations.AlterModelOptions(
            name='proof',
            options={'ordering': ['-created_at', '-pk'], 'verbose_name': 'Pièce justificative', 'verbose_name_plural': 'Pièces justificatives'},
        ),
        migrations.AddField(
            model_name='dossier',
            name='created_by',
            field=models.CharField(blank=True, max_length=180, verbose_name='Ouvert par'),
        ),
        migrations.AddField(
            model_name='expense',
            name='control_note',
            field=models.TextField(blank=True, verbose_name='Motif du contrôle'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Création'), ('updated', 'Modification'), ('submitted', 'Soumission'), ('reviewed', 'Mise en contrôle'), ('justified', 'Justification'), ('unjustified', 'Constat de non-justification'), ('approved', "Validation d'un justificatif"), ('rejected', "Rejet d'un justificatif"), ('proof_incomplete', 'Justificatif signalé incomplet'), ('proof_to_review', 'Justificatif remis à contrôler'), ('deleted', "Suppression d'un brouillon"), ('closed', 'Clôture'), ('proof_uploaded', 'Dépôt de justificatif'), ('proof_replaced', 'Remplacement de justificatif'), ('downloaded', 'Téléchargement'), ('imported', 'Import Excel')], max_length=32, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Identifiant'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dossiers', to='core.manager', verbose_name='Propriétaire'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dossiers', to='core.team', verbose_name='Équipe'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='beneficiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.beneficiary', verbose_name='Prospect / bénéficiaire'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.dossier', verbose_name='Dossier'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='core.expensetitle', verbose_name='Intitulé de dépenses'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='marketing_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='core.marketingcategory', verbose_name='Catégorie marketing'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='core.manager', verbose_name='Propriétaire'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='core.project', verbose_name='Projet'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='core.team', verbose_name='Équipe'),
        ),
        migrations.AlterField(
            model_name='proof',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proofs', to='expenses.dossier', verbose_name='Dossier'),
        ),
        migrations.AlterField(
            model_name='proof',
            name='replaces',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replaced_by', to='expenses.proof', verbose_name='Remplace'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at'], name='audit_date'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['country', 'created_at'], name='audit_pays_date'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user'], name='audit_utilisateur'),
        ),
        migrations.AddIndex(
            model_name='dossier',
            index=models.Index(fields=['country', 'status'], name='dossier_pays_statut'),
        ),
        migrations.AddIndex(
            model_name='dossier',
            index=models.Index(fields=['date'], name='dossier_date'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['budget', 'status'], name='depense_enveloppe_statut'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['country', 'status', 'date'], name='depense_pays_statut_date'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['date'], name='depense_date'),
        ),
        migrations.AddIndex(
            model_name='proof',
            index=models.Index(fields=['dossier', 'status'], name='piece_dossier_statut'),
        ),
        migrations.RunPython(reprendre_les_donnees, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='depense_montant_positif'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('justified_amount__gte', 0), ('justified_amount__lte', models.F('amount'))), name='depense_justifie_borne'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('original_amount__isnull', True), ('original_currency', ''), ('original_rate__isnull', True)), models.Q(models.Q(('original_currency', ''), _negated=True), ('original_amount__isnull', False), ('original_rate__isnull', False)), _connector='OR'), name='depense_devise_origine_coherente'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'draft'), ('budget__isnull', False), _connector='OR'), name='depense_declaree_imputee'),
        ),
    ]
