# Generated by Django 5.2.17 on 2026-09-04 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_journal_pays_protege'),
        ('expenses', '0009_numero_d_ordre_unique_par_pays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_entries', to='core.country', verbose_name='Pays'),
        ),
    ]
