# Generated by Django 5.2.17 on 2026-09-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_journal_pays_protege'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='reopen_note',
            field=models.TextField(blank=True, verbose_name='Motif de la réouverture'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Création'), ('updated', 'Modification'), ('submitted', 'Soumission'), ('reviewed', 'Mise en contrôle'), ('justified', 'Justification'), ('unjustified', 'Constat de non-justification'), ('approved', "Validation d'un justificatif"), ('rejected', "Rejet d'un justificatif"), ('proof_incomplete', 'Justificatif signalé incomplet'), ('proof_to_review', 'Justificatif remis à contrôler'), ('deleted', "Suppression d'un brouillon"), ('closed', 'Clôture'), ('reopened', 'Réouverture'), ('proof_uploaded', 'Dépôt de justificatif'), ('proof_replaced', 'Remplacement de justificatif'), ('downloaded', 'Téléchargement'), ('imported', 'Import Excel')], max_length=32, verbose_name='Action'),
        ),
    ]
