# Generated by Django 5.2.17 on 2026-09-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_reouverture_d_un_dossier'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='proof',
            constraint=models.UniqueConstraint(condition=models.Q(('replaces__isnull', True)), fields=('dossier', 'sha256'), name='piece_unique_par_dossier'),
        ),
    ]
