# Generated by Django 5.2.17 on 2026-09-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0004_controle_et_integrite"),
        ("core", "0014_capacite_responsable"),
        ("expenses", "0015_rectification"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="expense",
            name="depense_date",
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["-date", "-created_at", "-id"], name="depense_tri_liste"
            ),
        ),
    ]
