# Generated by Django 5.2.17 on 2026-09-25 12:10

"""Téléphone et e-mail des bénéficiaires (décision 93).

Le champ « Contact » était un texte libre, facultatif. Il devient deux
champs, ``phone`` et ``email`` — l'un des deux est exigé à la création et à
chaque modification (``BeneficiarySerializer``) — et le texte libre reste,
sous le nom « Autres coordonnées ».

Reprise : un contact existant qui **est** une adresse e-mail, ou **est** un
numéro de téléphone, passe dans le champ correspondant ; tout autre texte
(« M. Diallo, 77 123 45 67 ») reste où il était. Rien n'est perdu, rien
n'est deviné. Les bénéficiaires sans contact restent valides jusqu'à leur
prochaine modification.

La logique de reconnaissance est recopiée ici, figée, plutôt qu'importée de
``expenses.contacts`` : une migration doit rejouer demain ce qu'elle a fait
aujourd'hui.
"""

import re

from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.db import migrations, models


_TELEPHONE = re.compile(r"^\+?[0-9 ().\-]+$")


def _est_un_telephone(valeur):
    if not _TELEPHONE.match(valeur):
        return False
    return 6 <= sum(c.isdigit() for c in valeur) <= 15


def _est_un_email(valeur):
    try:
        validate_email(valeur)
    except ValidationError:
        return False
    return True


def ranger_les_contacts(apps, schema_editor):
    Beneficiary = apps.get_model("expenses", "Beneficiary")
    ranges = []
    for beneficiaire in Beneficiary.objects.exclude(contact="").order_by("pk"):
        valeur = beneficiaire.contact.strip()
        if _est_un_email(valeur):
            beneficiaire.email = valeur
        elif _est_un_telephone(valeur) and len(" ".join(valeur.split())) <= 32:
            beneficiaire.phone = " ".join(valeur.split())
        else:
            continue
        beneficiaire.contact = ""
        ranges.append(beneficiaire)
    Beneficiary.objects.bulk_update(ranges, ["email", "phone", "contact"], batch_size=500)


def remettre_les_contacts(apps, schema_editor):
    """Retour arrière : le téléphone ou l'e-mail repart dans le texte libre."""
    Beneficiary = apps.get_model("expenses", "Beneficiary")
    for beneficiaire in Beneficiary.objects.filter(contact="").exclude(phone="", email=""):
        beneficiaire.contact = beneficiaire.email or beneficiaire.phone
        beneficiaire.save(update_fields=["contact"])


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0017_brouillons_du_siege_rendus_au_pays"),
    ]

    operations = [
        migrations.AddField(
            model_name="beneficiary",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="E-mail"),
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="phone",
            field=models.CharField(blank=True, max_length=32, verbose_name="Téléphone"),
        ),
        migrations.AlterField(
            model_name="beneficiary",
            name="contact",
            field=models.CharField(
                blank=True, max_length=180, verbose_name="Autres coordonnées"
            ),
        ),
        migrations.RunPython(ranger_les_contacts, remettre_les_contacts),
    ]
