# Generated by Django 5.2.17 on 2026-10-02 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_motif_de_l_historique"),
        ("expenses", "0020_renommage_d_un_dossier"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="proof",
            name="piece_unique_par_dossier",
        ),
        migrations.AddField(
            model_name="proof",
            name="expense",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="proofs",
                to="expenses.expense",
                verbose_name="Ligne de dépense",
            ),
        ),
        migrations.AddConstraint(
            model_name="dossier",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind__isnull", False)),
                fields=("project", "kind"),
                name="unique_type_par_projet",
            ),
        ),
        migrations.AddConstraint(
            model_name="proof",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("expense__isnull", False), ("replaces__isnull", True)
                ),
                fields=("expense", "sha256"),
                name="piece_unique_par_ligne",
            ),
        ),
        migrations.AddConstraint(
            model_name="proof",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("expense__isnull", True), ("replaces__isnull", True)
                ),
                fields=("dossier", "sha256"),
                name="piece_unique_par_dossier",
            ),
        ),
    ]
