# Generated by Django 5.2.17 on 2026-10-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0021_piece_par_ligne_et_dossiers_predefinis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("created", "Création"),
                    ("updated", "Modification"),
                    ("submitted", "Soumission"),
                    ("reviewed", "Mise en contrôle"),
                    ("justified", "Justification"),
                    ("unjustified", "Constat de non-justification"),
                    ("approved", "Validation d'un justificatif"),
                    ("rejected", "Rejet d'un justificatif"),
                    ("proof_incomplete", "Justificatif signalé incomplet"),
                    ("proof_to_review", "Justificatif remis à contrôler"),
                    ("deleted", "Suppression d'un brouillon"),
                    ("closed", "Clôture"),
                    ("reopened", "Réouverture"),
                    ("rectification_requested", "Demande de rectification"),
                    ("rectification_decided", "Décision sur une rectification"),
                    ("rectified", "Rectification d'un constat"),
                    ("proof_uploaded", "Dépôt de justificatif"),
                    ("proof_replaced", "Remplacement de justificatif"),
                    ("downloaded", "Téléchargement"),
                    ("imported", "Import Excel"),
                    ("renamed", "Renommage"),
                    ("purged", "Remise à zéro des essais"),
                ],
                max_length=32,
                verbose_name="Action",
            ),
        ),
    ]
