# Generated by Django 5.1.6 on 2026-09-01 19:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_country_country_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('year', models.PositiveIntegerField(verbose_name='Année')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant')),
                ('overrun_policy', models.CharField(choices=[('block', 'Bloquer'), ('warn', 'Alerter'), ('approval', 'Soumettre à approbation')], default='block', max_length=20, verbose_name='Politique de dépassement')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='core.country', verbose_name='Pays')),
                ('project', models.ForeignKey(blank=True, help_text="Renseigné pour une sous-enveloppe ; vide pour l'enveloppe du pays.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='core.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Budget',
                'ordering': ['-year', 'country__name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetReallocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant')),
                ('reason', models.TextField(verbose_name='Justification')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Refusée')], default='pending', max_length=20, verbose_name='Statut')),
                ('requested_by', models.CharField(blank=True, max_length=180, verbose_name='Demandée par')),
                ('decided_by', models.CharField(blank=True, max_length=180, verbose_name='Décidée par')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Décidée le')),
                ('decision_note', models.TextField(blank=True, verbose_name='Motif de la décision')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reallocations_out', to='budget.budget', verbose_name='Enveloppe source')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reallocations_in', to='budget.budget', verbose_name='Enveloppe destinataire')),
            ],
            options={
                'verbose_name': 'Réallocation budgétaire',
                'verbose_name_plural': 'Réallocations budgétaires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(help_text='ISO 4217', max_length=3, verbose_name='Devise')),
                ('rate_to_xof', models.DecimalField(decimal_places=6, help_text='Nombre de FCFA pour une unité de la devise.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='Taux vers le FCFA')),
                ('valid_from', models.DateField(verbose_name='En vigueur depuis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Taux de change',
                'verbose_name_plural': 'Taux de change',
                'ordering': ['currency', '-valid_from'],
                'constraints': [models.UniqueConstraint(fields=('currency', 'valid_from'), name='unique_taux_devise_date')],
            },
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', True)), fields=('country', 'year'), name='unique_enveloppe_pays_annee'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('country', 'project', 'year'), name='unique_sous_enveloppe_projet_annee'),
        ),
    ]
