# Generated by Django 5.1.6 on 2026-09-02 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
        ('core', '0004_alter_changelog_model_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='budget',
            name='unique_enveloppe_pays_annee',
        ),
        migrations.AddField(
            model_name='budget',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='core.manager', verbose_name='Manager'),
        ),
        migrations.AddField(
            model_name='budget',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='core.team', verbose_name='Équipe'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='core.project', verbose_name='Projet'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(condition=models.Q(('manager__isnull', True), ('project__isnull', True), ('team__isnull', True)), fields=('country', 'year'), name='unique_enveloppe_pays_annee'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('country', 'team', 'year'), name='unique_sous_enveloppe_equipe_annee'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('country', 'manager', 'year'), name='unique_sous_enveloppe_manager_annee'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('manager__isnull', True), ('project__isnull', True), ('team__isnull', True)), models.Q(('manager__isnull', True), ('project__isnull', False), ('team__isnull', True)), models.Q(('manager__isnull', True), ('project__isnull', True), ('team__isnull', False)), models.Q(('manager__isnull', False), ('project__isnull', True), ('team__isnull', True)), _connector='OR'), name='sous_enveloppe_une_seule_dimension'),
        ),
    ]
