# Generated by Django 5.1.6 on 2026-09-04 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_default_overrun_policy'),
        ('core', '0008_controle_et_integrite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-year', 'country__name', '-pk'], 'verbose_name': 'Budget'},
        ),
        migrations.AlterModelOptions(
            name='budgetreallocation',
            options={'ordering': ['-created_at', '-pk'], 'verbose_name': 'Réallocation budgétaire', 'verbose_name_plural': 'Réallocations budgétaires'},
        ),
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'ordering': ['currency', '-valid_from', '-pk'], 'verbose_name': 'Taux de change', 'verbose_name_plural': 'Taux de change'},
        ),
        migrations.AlterField(
            model_name='budget',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='core.country', verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='core.manager', verbose_name='Manager'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='overrun_policy',
            field=models.CharField(choices=[('block', 'Bloquer'), ('warn', 'Alerter'), ('approval', 'Soumettre à approbation')], default='block', max_length=20, verbose_name='Politique de dépassement'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='core.project', verbose_name='Projet'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='core.team', verbose_name='Équipe'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['country', 'year', 'is_active'], name='budget_pays_annee_actif'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='budget_montant_positif_ou_nul'),
        ),
        migrations.AddConstraint(
            model_name='budgetreallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='reallocation_montant_positif'),
        ),
        migrations.AddConstraint(
            model_name='budgetreallocation',
            constraint=models.CheckConstraint(condition=models.Q(('source', models.F('target')), _negated=True), name='reallocation_source_differente_cible'),
        ),
        migrations.AddConstraint(
            model_name='budgetreallocation',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'pending'), ('decided_at__isnull', False), _connector='OR'), name='reallocation_decision_datee'),
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.CheckConstraint(condition=models.Q(('rate_to_xof__gt', 0)), name='taux_strictement_positif'),
        ),
    ]
