# Generated by Django 5.1.6 on 2026-09-01 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nom')),
                ('code', models.CharField(help_text='ISO 3166-1 alpha-2', max_length=2, unique=True, verbose_name='Code ISO')),
                ('currency', models.CharField(help_text='ISO 4217', max_length=3, verbose_name='Devise')),
                ('currency_symbol', models.CharField(blank=True, max_length=4, verbose_name='Symbole devise')),
                ('timezone', models.CharField(default='UTC', max_length=64, verbose_name='Fuseau horaire')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Pays',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('name', models.CharField(max_length=180, verbose_name='Nom')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('title', models.CharField(blank=True, max_length=180, verbose_name='Fonction')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(choices=[('country', 'Pays'), ('manager', 'Manager'), ('team', 'Équipe'), ('cost_center', 'Centre de coûts'), ('project', 'Projet'), ('expense_title', 'Intitulé de dépenses'), ('marketing_category', 'Catégorie marketing')], max_length=32, verbose_name='Entité')),
                ('object_id', models.PositiveIntegerField(verbose_name="Identifiant d'entité")),
                ('label', models.CharField(max_length=250, verbose_name='Libellé')),
                ('action', models.CharField(choices=[('created', 'Création'), ('updated', 'Mise à jour'), ('reassigned', 'Changement de rattachement'), ('deactivated', 'Désactivation'), ('reactivated', 'Réactivation')], max_length=20, verbose_name='Action')),
                ('from_value', models.TextField(blank=True, verbose_name='Valeur précédente')),
                ('to_value', models.TextField(blank=True, verbose_name='Nouvelle valeur')),
                ('changed_fields', models.JSONField(blank=True, default=list, verbose_name='Champs modifiés')),
                ('performed_by', models.CharField(blank=True, max_length=180, verbose_name='Par')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Le')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='core.country', verbose_name='Pays')),
            ],
            options={
                'verbose_name': 'Historique',
                'verbose_name_plural': 'Historiques',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='country',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='countries', to='core.manager', verbose_name='Manager(s)'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('name', models.CharField(max_length=180, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('planned', 'Planifié'), ('active', 'En cours'), ('on_hold', 'En pause'), ('completed', 'Terminé')], default='planned', max_length=20, verbose_name='Statut')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Budget')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.country', verbose_name='Pays')),
            ],
            options={
                'verbose_name': 'Projet',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('name', models.CharField(max_length=180, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='core.country', verbose_name='Pays')),
            ],
            options={
                'verbose_name': 'Équipe',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('name', models.CharField(max_length=180, verbose_name='Libellé')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_centers', to='core.country', verbose_name='Pays')),
            ],
            options={
                'verbose_name': 'Centre de coûts',
                'ordering': ['code'],
                'unique_together': {('country', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ExpenseTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('label', models.CharField(max_length=180, verbose_name='Intitulé')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_titles', to='core.country', verbose_name='Pays')),
            ],
            options={
                'verbose_name': 'Intitulé de dépenses',
                'ordering': ['label'],
                'unique_together': {('country', 'label')},
            },
        ),
        migrations.CreateModel(
            name='MarketingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('name', models.CharField(max_length=180, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_categories', to='core.country', verbose_name='Pays')),
            ],
            options={
                'verbose_name': 'Catégorie marketing',
                'ordering': ['name'],
                'unique_together': {('country', 'name')},
            },
        ),
    ]
