# Generated by Django 5.1.6 on 2026-09-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='action',
            field=models.CharField(choices=[('created', 'Création'), ('updated', 'Mise à jour'), ('reassigned', 'Changement de rattachement'), ('deactivated', 'Désactivation'), ('reactivated', 'Réactivation'), ('deleted', 'Suppression')], max_length=20, verbose_name='Action'),
        ),
    ]
