# Generated by Django 5.1.6 on 2026-09-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_changelog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_ref',
            field=models.CharField(blank=True, help_text='Identifiant fonctionnel utilisé par le siège, ex. CT-01.', max_length=10, null=True, unique=True, verbose_name='Identifiant pays'),
        ),
    ]
