# Generated by Django 5.1.6 on 2026-09-02 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_country_country_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='model_name',
            field=models.CharField(choices=[('country', 'Pays'), ('manager', 'Manager'), ('team', 'Équipe'), ('cost_center', 'Centre de coûts'), ('project', 'Projet'), ('expense_title', 'Intitulé de dépenses'), ('marketing_category', 'Catégorie marketing'), ('budget', 'Enveloppe budgétaire'), ('reallocation', 'Réallocation budgétaire'), ('exchange_rate', 'Taux de change')], max_length=32, verbose_name='Entité'),
        ),
    ]
