# Generated by Django 5.1.6 on 2026-09-02 12:20

import core.africa
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_perimetre_africain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(help_text='ISO 3166-1 alpha-2 ; la plateforme ne suit que des pays africains.', max_length=2, unique=True, validators=[core.africa.validate_african_country], verbose_name='Code ISO'),
        ),
    ]
