# Generated by Django 5.2.17 on 2026-09-04 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_equipe_et_projet_uniques_par_pays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='history', to='core.country', verbose_name='Pays'),
        ),
    ]
