# Generated by Django 5.2.17 on 2026-09-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_capacite_responsable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changelog",
            name="model_name",
            field=models.CharField(
                choices=[
                    ("country", "Pays"),
                    ("manager", "Manager"),
                    ("team", "Équipe"),
                    ("cost_center", "Centre de coûts"),
                    ("project", "Projet"),
                    ("expense_title", "Intitulé de dépenses"),
                    ("marketing_category", "Catégorie marketing"),
                    ("budget", "Enveloppe budgétaire"),
                    ("reallocation", "Réallocation budgétaire"),
                    ("exchange_rate", "Taux de change"),
                    ("workflow_configuration", "Configuration du workflow"),
                    ("user", "Compte utilisateur"),
                    ("beneficiary", "Bénéficiaire"),
                ],
                max_length=32,
                verbose_name="Entité",
            ),
        ),
    ]
