# Generated by Django 5.2.17 on 2026-10-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_projets_types_et_numerotes"),
    ]

    operations = [
        migrations.AddField(
            model_name="changelog",
            name="motif",
            field=models.TextField(blank=True, verbose_name="Motif"),
        ),
    ]
